import Link from "next/link";
import { ArrowRight, BookOpen, CheckCircle2, Clock3, CreditCard, Globe2, LockKeyhole, MessageCircle, ShieldCheck } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { Button } from "@/components/ui/button";
import { ServicesGrid } from "@/components/ServicesGrid";
import { PricingCalculator } from "@/components/PricingCalculator";
import type { Service } from "@/lib/types";

export default async function HomePage() {
  const supabase = await createClient();
  const { data: services } = await supabase.from("services").select("*").order("is_featured", { ascending: false }).order("created_at", { ascending: true });
  const servicesData: Service[] = (services || []).map((service) => ({ ...service, features: Array.isArray(service.features) ? service.features : [] }));
  return <div>
    <section className="relative overflow-hidden bg-slate-950 py-20 text-white lg:py-28"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(14,165,233,.22),transparent_45%)]"/><div className="container relative mx-auto grid items-center gap-12 px-6 lg:grid-cols-[1.2fr_.8fr]">
      <div className="space-y-7"><div className="inline-flex items-center gap-2 rounded-full border border-sky-400/30 bg-sky-400/10 px-4 py-2 text-sm text-sky-200"><Globe2 className="h-4 w-4"/>Support for UK &amp; USA students</div><h1 className="max-w-4xl text-4xl font-bold tracking-tight text-white sm:text-5xl lg:text-6xl">Clear, ethical academic support—built around your goals.</h1><p className="max-w-2xl text-lg leading-relaxed text-slate-300">Get tutoring, research planning, editing and study support across UK and US academic conventions. Keep every instruction, file, message and payment in one secure account.</p><div className="flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="gap-2"><Link href="/order">Get a secure quote<ArrowRight className="h-5 w-5"/></Link></Button><Button asChild size="lg" variant="outline" className="border-white/30 bg-transparent text-white hover:bg-white/10 hover:text-white"><Link href="/services">Explore services</Link></Button></div></div>
      <div className="grid gap-4">{[[CreditCard,"Transparent USD checkout","See the server-verified total before paying securely with Paystack."],[MessageCircle,"One order workspace","Track progress, upload references and communicate from your dashboard."],[ShieldCheck,"Honest service boundaries","Tutoring and editorial support designed to protect academic integrity."]].map(([Icon,title,copy])=><div key={String(title)} className="rounded-2xl border border-white/10 bg-white/5 p-6 backdrop-blur"><Icon className="mb-3 h-6 w-6 text-sky-400"/><h2 className="font-semibold text-white">{String(title)}</h2><p className="mt-1 text-sm leading-relaxed text-slate-300">{String(copy)}</p></div>)}</div>
    </div></section>
    <section className="border-b bg-muted/30 py-10"><div className="container mx-auto grid gap-6 px-6 sm:grid-cols-2 lg:grid-cols-4">{[[LockKeyhole,"Private account","Order information is access-controlled"],[CreditCard,"Recoverable payment","Resume unpaid orders from your dashboard"],[Clock3,"Deadline planning","Choose a clear delivery or session date"],[BookOpen,"UK & US conventions","Harvard, OSCOLA, APA, MLA and Chicago"]].map(([Icon,title,copy])=><div key={String(title)} className="flex gap-3"><Icon className="mt-1 h-5 w-5 shrink-0 text-primary"/><div><h2 className="font-semibold">{String(title)}</h2><p className="text-sm text-muted-foreground">{String(copy)}</p></div></div>)}</div></section>
    <section id="services" className="py-20"><div className="container mx-auto px-6"><div className="mx-auto mb-12 max-w-2xl text-center"><p className="mb-2 font-semibold text-primary">ACADEMIC SUPPORT</p><h2 className="text-3xl font-bold">Choose the help you actually need</h2><p className="mt-3 text-muted-foreground">From a focused proofread to dissertation guidance, live tutoring and exam preparation.</p></div><ServicesGrid services={servicesData}/></div></section>
    <section id="how-it-works" className="bg-muted/40 py-20"><div className="container mx-auto px-6"><div className="mx-auto mb-12 max-w-2xl text-center"><h2 className="text-3xl font-bold">A simple three-step workflow</h2></div><div className="mx-auto grid max-w-5xl gap-6 md:grid-cols-3">{[["01","Describe your goal","Choose a service, add your brief and upload useful reference material."],["02","Review and pay","Confirm the price, apply a valid promo code and pay securely in USD through Paystack."],["03","Track your support","Follow progress in your dashboard, send messages and access delivered files."]].map(([n,t,d])=><div key={n} className="rounded-2xl border bg-background p-7"><span className="text-3xl font-black text-primary/30">{n}</span><h3 className="mt-4 text-lg font-bold">{t}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{d}</p></div>)}</div></div></section>
    <section className="py-20"><div className="container mx-auto px-6"><div className="mx-auto mb-12 max-w-2xl text-center"><h2 className="text-3xl font-bold">Estimate before you order</h2><p className="mt-3 text-muted-foreground">Standard written-support estimates vary by length, academic level and deadline. Classes and exam-preparation sessions use per-class or per-exam pricing.</p></div><PricingCalculator basePrice={18}/></div></section>
    <section className="bg-muted/40 py-20"><div className="container mx-auto max-w-5xl px-6"><div className="grid gap-10 lg:grid-cols-2"><div><p className="font-semibold text-primary">TRUST THROUGH TRANSPARENCY</p><h2 className="mt-2 text-3xl font-bold">No invented reviews or mystery promises</h2><p className="mt-4 leading-relaxed text-muted-foreground">We only publish customer testimonials after they can be connected to a genuine completed order and the customer has approved publication. Until then, we show safeguards you can verify yourself.</p></div><div className="space-y-4">{["Server-verified prices and payment references","Printable receipts for confirmed payments","Clear refund and cancellation terms","Support contact available before you order"].map(x=><div key={x} className="flex gap-3 rounded-xl border bg-background p-4"><CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-500"/><span>{x}</span></div>)}</div></div></div></section>
    <section className="py-20"><div className="container mx-auto max-w-3xl px-6"><div className="rounded-3xl bg-primary p-10 text-center text-white md:p-14"><h2 className="text-3xl font-bold text-white">Ready to plan your next step?</h2><p className="mx-auto mt-3 max-w-xl text-white/80">Start a saved order, review the exact total and decide whether to pay. You can cancel an unpaid order at any time.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Button asChild size="lg" variant="secondary"><Link href="/order">Start an order</Link></Button><Button asChild size="lg" variant="outline" className="border-white/40 bg-transparent text-white hover:bg-white/10 hover:text-white"><Link href="/faq">Read the FAQ</Link></Button></div></div></div></section>
  </div>;
}
